export const JOIN_SESSION = 'JOIN_SESSION';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const ADD_USER = 'ADD_USER';
export const USERS_LIST = 'USERS_LIST';

export const START_VOTING_SESSION = 'START_VOTING_SESSION';
export const VOTING_SESSION_STARTED = 'VOTING_SESSION_STARTED';
export const CANCEL_VOTING_SESSION = 'CANCEL_VOTING_SESSION';
export const VOTING_SESSION_CANCELLED = 'VOTING_SESSION_CANCELLED';
export const FINISH_VOTING_SESSION = 'FINISH_VOTING_SESSION';
export const CAST_VOTE = 'CAST_VOTE';
export const VOTE_ACCEPTED = 'VOTE_ACCEPTED';
export const VOTING_UPDATE = 'VOTING_UPDATE';
export const VOTING_FINISHED = 'VOTING_FINISHED';
